apiVersion: v1
kind: Service
metadata:
  name: grafana-dashboard-nodeport
  namespace: monitoring
spec:
  selector:
     app.kubernetes.io/component: grafana
     app.kubernetes.io/name: grafana
     app.kubernetes.io/part-of: kube-prometheus
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30300