apiVersion: v1
kind: Service
metadata:
  name: minio-prometheus
  namespace: minio-cluster
  labels:
    minio: minio-prometheus
    Minio: minio-prometheus
spec:
  selector:
    v1.min.io/tenant: minio-tenant
  ports:
    - port: 9000
      name: https
