apiVersion: v1
kind: Service
metadata:
  namespace: minio-cluster
  name: minio-cluster-console-nodeport
spec:
  selector:
    v1.min.io/tenant: minio-tenant
  type: NodePort
  ports:
    - port: 9443
      protocol: TCP
      targetPort: 9443
      nodePort: 30443