apiVersion: v1
kind: Service
metadata:
  namespace: minio-cluster
  name: minio-cluster-api
spec:
  selector:
    v1.min.io/tenant: minio-tenant
  type: NodePort
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
      nodePort: 30009